### ISSUE TITLE
Re-do UI

### ISSUE THREAD

**Issue by yasserhussain1110** [yasserhussain1110/sona-sarovar-trust#1]
UI isn't very professional right now. http://ec2-13-126-102-159.ap-south-1.compute.amazonaws.com.  
We should re-work it.

**Comment by mkoron** [comment]
I am willing to help

**Comment by yasserhussain1110** [comment]
Sorry @mkoron . @zsoltime has already started working on this issue. Please keep an eye on this issue tracker, I'm sure other issues will keep cropping up.

**Comment by mkoron** [comment]
No problem, @yasserhussain1110. I only saw the announcement on chingu yesterday, so I thought to ask if help was needed.

**Comment by edward-hong** [comment]
Sorry I've been busy the last few days. Will keep an eye out for any further issues
